### ISSUE TITLE
作業分野の切り分け

### ISSUE THREAD

**Issue by BPkuma** [BPkuma/KonnaKanji#9]
プロトタイプ完成以降の作業分野は大別すると以下のようになるかと思うんですが、どうでしょう？<br>
1と2はある意味でバックエンド的な作業で、3はがっつりフロントエンドの作業になりますかね。<br>
3は結構大変そうなので人員配分は 1 : 1 : 2 が適切かと思いました。<br>
ご意見をコメントでお願いしまーす！<br><br>

1.  ユーザーが選択した回答を納めた配列データから、どの画像を選び出すかのアルゴリズムを考え実装する作業<br><br>
2.   1と連携して、選び出された画像の組み合わせによって配置するフィールドのフォーメーションをどのようにしたら「漢字としてそれっぽく見えるか」を考え実装する作業<br>なんとなくですが、今ある問題文と回答をセットにした多元配列の構造や要素から設計し直す必要がある気が、、、<br><br>
3. 主にCSS（場合によってはHTMLのタグ要素や初期配置も変更する必要あり？）を作り込んで見た目や動き（UI）を洗練させていく作業<br><br>

**Comment by thinkinkiwi** [comment]
下記の分担で、各自のペースで進める。各自のペースで進める。（大事なことなので2回言いました）

1．大桃さん
2．テル
3．渡部さん
4．素材作り（←New!!）：宮東さん

機能面は宮東さん以外で一旦分担して作成し、宮東さんには素材づくりに取り組んでいただく。
